application: thermal-sensing
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:

- remote_api: on

libraries:

- name: jinja2
  version: latest

handlers:

- url: /public
  static_dir: public

- url: /.*
  script: main.application